### ISSUE TITLE
Allow specifying an external struct size hint

### ISSUE THREAD

**Issue by westy92** [DKerp/get-size#5]
For external structs, we can use `#[get_size(ignore)]`, which is great. However, if I know what the size of the external struct will be, it would be nice to be able to add a hint. This could look like `#[get_size(ignore, 24)]`.

**Comment by DKerp** [comment]
I implemented it, but used a different naming. I think

**Comment by DKerp** [comment]
I implemented it, but used a different naming. You can now use `#[get_size(size = 24)]` to specify a fixed heap size for a certain named struct field.
